bnb-chain/tss-lib

README.md
Currently p2pCtx variable name in README is inconsistent,
namely `ctx` in L55 but `p2pCtx` in L56.
We'd better keep it consistent for better understanding.
=> doc: keep variable name consistent in README

ecdsa/keygen/local_party.go, ecdsa/keygen/local_party_test.go, ecdsa/keygen/save_data.go, ecdsa/keygen/test_utils.go, ecdsa/resharing/local_party.go, ecdsa/resharing/local_party_test.go, ecdsa/resharing/round_1_old_step_1.go, ecdsa/resharing/round_5_new_step_3.go, ecdsa/resharing/rounds.go, ecdsa/signing/local_party.go, ecdsa/signing/local_party_test.go, ecdsa/signing/prepare.go, tss/party.go, tss/party_id.go
If the set of parties is not contiguous or does not begin from keygen index 0 when provided to the signing code, the save data must be re-indexed/filtered outside the lib to make signing work. 
This patch offers a workaround whereby the save data is temporarily re-built for the signing rounds to contain the expected ordered lists, removing the need for app-layer code to do that for a non-contiguous set of signers.
=> ecdsa: reindex input data for the given signing parties

ecdsa/keygen/local_party_test.go
When the fixture files were deleted this test was stalling, waiting on an empty set of parties.
=> ecdsa/keygen/*test: fix stall when generating new fixtures

eddsa/resharing/messages.go
round4 ack message should be register to avoid proto unmarshal error: `any: message type "" isn't linked in"`
=> fix bug: register DGRound4Message for eddsa resharing

crypto/mta/range_proof.go
rename N2&modN2 in RangeProofAlice.Verify to same style in RangeProofAlice.Prove
=> style(mta::RangeProofAlice): rename for more consistent var name

crypto/commitments/commitment.go, crypto/schnorr/schnorr_proof.go
in vss::Share::Verify & mta::ProofBob::Verify & all other  ValidateBasic()/Validate(), boolean computations are returned directly. 
+ https://github.com/binance-chain/tss-lib/blob/e860e36eaaa63afcaf1e5a0ed79b6f56362e88c8/crypto/vss/feldman_vss.go#L93
+ https://github.com/binance-chain/tss-lib/blob/e860e36eaaa63afcaf1e5a0ed79b6f56362e88c8/crypto/mta/proofs.go#L276
+ https://github.com/binance-chain/tss-lib/blob/e860e36eaaa63afcaf1e5a0ed79b6f56362e88c8/crypto/mta/proofs.go#L279
+ https://github.com/binance-chain/tss-lib/blob/e860e36eaaa63afcaf1e5a0ed79b6f56362e88c8/crypto/ecpoint.go#L76
+ ...
However, this is not the case in commitment and schnorr_proof package. 
This PR refactor them to consistent verification style, and **may save condition branch executions if being compiled without …
=> style: refactor crypto lib to consistent verification style

eddsa/resharing/round_1_old_step_1.go, eddsa/signing/prepare.go
fix eddsa reshare panic when old committee number exceed t+1
=> fix: reshare for eddsa panic if old committee exceed t+1

ecdsa/signing/finalize.go, ecdsa/signing/local_party_test.go
The R and S might not be less than 32 bytes, if we return such R and S and the client code concatenates these two bytes together, the signature would not be 64 bytes. Such signature would fail for blockchains (for example Ethereum) that check the signature length: https://github.com/ethereum/go-ethereum/blob/master/crypto/secp256k1/secp256.go#L169-L171
=> fix R and S may not be 32 bytes

crypto/vss/feldman_vss.go
We need to ensure that:
- all indexes are non-zero,
- all indexes are non-zero modulo the curve order,
- all indexes are unique modulo the curve order.
The first two are guarded in `CheckIndexes` function by:
```
vMod := new(big.Int).Mod(v, ec.Params().N)
if vMod.Cmp(zero) == 0 {
return nil, errors.New("party index should not be 0")
}
```
The last one is guarded by:
```
vModStr := vMod.String()
if _, ok := visited[vModStr]; ok {
return nil, fmt.Errorf("duplicate indexes %s", vModStr)
}
visited[vModStr] = struct{}{}
```
`CheckIndexes` was additionally normalizing identifiers mod elliptic curve order.
This was not really needed and could cause problems during signing.
=> Do not normalize IDs of Shamir's Secret Sharing

ecdsa/keygen/save_data.go, ecdsa/signing/prepare.go, eddsa/keygen/save_data.go, eddsa/signing/prepare.go
Following reply on vss fix that adding defense when Ks mismatch
=> Additional check when Ks mismatch in savedata and sortedID

ecdsa/keygen/local_party_test.go, ecdsa/keygen/round_2.go
In the test, shares is collected excluding Pj's own share. It causes problem in like 2/1 threshold setting, for omitting own share will result in no enough threshold+1 shares can be collected
=> Fix for ECDSA keygen test

common/safe_prime.go, common/safe_prime_test.go, crypto/mta/range_proof_test.go, crypto/mta/share_protocol_test.go, crypto/paillier/paillier.go, crypto/paillier/paillier_test.go, ecdsa/keygen/prepare.go, ecdsa/keygen/prepare_test.go
Refs [#3161](https://github.com/keep-network/keep-core/issues/3161)
I am marking this PR as a draft hoping for an internal review process before I open a PR to `bnb-chain/tss-lib`.
Generating DKG pre-parameters is a computationally expensive operation. As `GeneratePreParams` documentation explains, it is recommended to do it out of band. Keep ECDSA (TBTC) client has a [pre-parameters](https://github.com/keep-network/keep-core/blob/main/pkg/tecdsa/dkg/params_pool.go) pool from which the DKG process pulls pre-parameters to do not have the entire group wait with kicking off DKG until pre-parameters are generated. This approach was sufficient for TBTC v1 when signing groups were 3-of-3. For TBTC v2, we need much larger signing groups (51-of-100) and for clients having multiple seats in the …
=> Allow to stop pre-parameters generator with a context

crypto/mta/proofs.go, crypto/mta/range_proof.go
Add some checks according to report
=> Add check in mta_proof

ecdsa/keygen/dln_verifier.go, ecdsa/keygen/dln_verifier_test.go, ecdsa/keygen/round_1.go, ecdsa/keygen/round_2.go, ecdsa/resharing/round_2_new_step_1.go, ecdsa/resharing/round_4_new_step_2.go, tss/params.go
Verification of discrete logarithm proofs is the most expensive part of threshold ECDSA key generation for large groups. In round 2 of key generation, the local party needs to verify proofs received from all other parties. The cost of a call to `dlnProof.Verify` measured on Darwin/arm64 Apple M1 max is 341758528 ns/op - see `BenchmarkDlnProof_Verify`. There are two proofs that need to be verified during the key generation so assuming there are two cores available exclusively for this work, the verification of 100 messages takes about 35 seconds. For a group size of 1000, the verification takes about 350 seconds. The verification is performed in separate goroutines with no control over the number of goroutines created. When executing the protocol locally, during the development, for a …
=> Improve DLN proof verification performance for large signing groups

common/hash.go
Make hash encoding of tagged version align with non-tagged version. Borrowed from https://github.com/IoFinnet/threshlib/blob/master/common/hash/hash.go
=> Update tagged version hash encoding

ecdsa/keygen/round_3.go, eddsa/keygen/round_3.go
error handlings in other places are of different style. This PR aims to make the error handling style more consistent
=> style: refactor to more consistent error handlings style 

common/safe_prime.go
Since there're only `concurrency` goroutines and each will at most send to `errCh` once, so a size of `concurrency` will be enough.
=> [nit] fix comment and minor optimize `GetRandomSafePrimesConcurrent`

common/random.go
`MustGetRandomInt`(which calls `rand.Int`) always returns a non-negative big int, so there's no need to check against zero at the caller side.
```golang
func rand.Int(rand io.Reader, max *big.Int) (n *big.Int, err error)
Int returns a uniform random value in [0, max). It panics if max <= 0.
```
=> [nit] remove unnecessary cmp

crypto/vss/feldman_vss.go
`samplePolynomial` has already assigned `secret` to the `0` index, so no need to assign again.
=> [nit] remove unnecessary assignment

ecdsa/signing/finalize.go, ecdsa/signing/local_party.go, ecdsa/signing/local_party_test.go, eddsa/signing/finalize.go, eddsa/signing/local_party.go, eddsa/signing/local_party_test.go, eddsa/signing/round_3.go
=> fix signing issue if the message is leading with 0x00
